volumes:
  spending-tracker:
    external: true
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_HOST: http://localhost:3000
      WAIT_HOSTS: db:5432
      PORT: 8000
  db:
    image: postgres:14.5-bullseye
    build: 
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - spending-tracker:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}